scrape_configs:
  - job_name: 'bijmantra-backend'
    metrics_path: '/metrics'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: bijmantra-backend
        action: keep
      - source_labels: [__meta_kubernetes_pod_container_port_number]
        regex: '8000'
        action: keep
