apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bijmantra-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - api.bijmantra.org
    secretName: bijmantra-tls
  rules:
  - host: api.bijmantra.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bijmantra-backend-service
            port:
              number: 80
